version: "3"
services:
  db:
    restart: always
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=activity_feed
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 54032:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-conf:/etc/postgresql
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  db-data:
    driver: local
  db-conf:
    driver: local
  